		<footer>
			<div id="footer">
				<div class="social">
					<a href="#facebook">Facebook</a>
					<a href="#twitter">Twitter</a>
				</div>
				<address>
					<p>43 Fitzwilliam Square,<br>Dublin 2, Ireland</p>
				</address>
				<div class="contact">
					<a href="tel:35316619206">T. +353 1 661 9206</a>
					<a href="mailto:info@lawrenceandlong?subject=hello">E. info@lawrenceandlong.com</a>
				</a></div>
			</div>
		</footer>

	</section><!-- .page -->

	<script data-main="<?php echo $config->urls->templates?>dist/scripts/main" src="<?php echo $config->urls->templates?>dist/bower_components/requirejs/require.js"></script>
</body>
</html>