		<footer>
			<div id="footer">
				<p><a id="facebook" href="#facebook">Facebook</a><a id="twitter" href="#twitter">Twitter</a><a id="vimeo" href="#vimeo">Vimeo</a>43 Fitzwilliam Square, Dublin 2, Ireland</p>

				<p><a href="tel:35316619206">T. +353 1 661 9206</a>&nbsp;&nbsp;&nbsp;<a href="mailto:info@lawrenceandlong?subject=hello">E. info@lawrenceandlong.com</a></p>

			</div>
		</footer>


	</section><!-- .page -->
	<script data-main="<?php echo $config->urls->templates?>dist/scripts/8640302b.main" src="<?php echo $config->urls->templates?>dist/bower_components/requirejs/require.js"></script>
</body>
</html>